# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('endTime', models.CharField(max_length=50)),
                ('startTime', models.CharField(max_length=50)),
                ('allDay', models.BooleanField(default=False)),
            ],
        ),
    ]
