# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='endTime',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='events',
            name='startTime',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
