# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181008_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
